In [1]:
import pandas as pd
from fuzzywuzzy import process

# Read the CSV file into DataFrame
stock_df = pd.read_csv(r"C:\Users\DELL\Desktop\Projects\LOC 6.0\Categories_Mapping.csv")
sector_definitions = pd.read_csv(r"C:\Users\DELL\Desktop\Projects\LOC 6.0\Sector_Definitions.csv")

C:\Users\DELL\anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [2]:
stock_df.head(5)

,Ticker,Name,Sector,Industry
0,20MICRONS,20 Microns Limited,Mining,Mining
1,360ONE,360 ONE WAM LIMITED,Finance,Finance
2,3IINFOLTD,3i Infotech Limited,COMPUTERS - SOFTWARE,COMPUTERS - SOFTWARE
3,3MINDIA,3M India Limited,Diversified Commercial Services,Diversified Commercial Services
4,5PAISA,5Paisa Capital Limited,Financial Services,Financial Services

In [3]:
sector_definitions.head(5)

,Macro\nEconomic\nSector,Sector,Industry,Basic Industry,Definition
0,Commodities,Chemicals,Chemicals &\nPetrochemicals,Commodity\nChemicals,Manufacturers of basic and industrial\nchemica...
1,Commodities,Chemicals,Chemicals &\nPetrochemicals,Specialty\nChemicals,Manufacturers of chemicals used in the\nmanufa...
2,Commodities,Chemicals,Chemicals &\nPetrochemicals,Carbon Black,Manufacturers of carbon black
3,Commodities,Chemicals,Chemicals &\nPetrochemicals,Dyes And Pigments,"Manufacturer, supplier and distributor of\ndye..."
4,Commodities,Chemicals,Chemicals &\nPetrochemicals,Explosives,"Manufacturer, supplier and exporter of\ncommer..."

In [4]:
# Function to find the most similar sector or industry
def find_similar_sector_or_industry(query, choices):
    match = process.extractOne(query, choices)
    return match[0] if match else None

# Add definitions to stock_df
for index, row in stock_df.iterrows():
    sector = row['Sector']
    industry = row['Industry']
    
    # Find similar sector in sector_definitions
    similar_sector = find_similar_sector_or_industry(sector, sector_definitions['Sector'])
    
    # Find similar industry in sector_definitions
    similar_industry = find_similar_sector_or_industry(industry, sector_definitions['Industry'])
    
    # Use similar sector or industry to get definition
    if similar_sector:
        definition = sector_definitions.loc[sector_definitions['Sector'] == similar_sector, 'Definition'].iloc[0]
    elif similar_industry:
        definition = sector_definitions.loc[sector_definitions['Industry'] == similar_industry, 'Definition'].iloc[0]
    else:
        definition = 'No definition found'
    
    # Assign definition to stock_df
    stock_df.at[index, 'Definition'] = definition

In [6]:
stock_df

,Ticker,Name,Sector,Industry,Definition
0,20MICRONS,20 Microns Limited,Mining,Mining,Manufacturers and distributor of ferro\nsilico...
1,360ONE,360 ONE WAM LIMITED,Finance,Finance,Financial Institutions as defined under\nSecti...
2,3IINFOLTD,3i Infotech Limited,COMPUTERS - SOFTWARE,COMPUTERS - SOFTWARE,Companies engaged in the production of\nrenewa...
3,3MINDIA,3M India Limited,Diversified Commercial Services,Diversified Commercial Services,Companies providing dredging and related\nserv...
4,5PAISA,5Paisa Capital Limited,Financial Services,Financial Services,Financial Institutions as defined under\nSecti...
...,...,...,...,...,...
1457,ZOTA,Zota Health Care LImited,Pharmaceuticals,Pharmaceuticals,Manufacturers of basic and industrial\nchemica...
1458,ZUARI,Zuari Agro Chemicals Limited,FERTILIZERS,FERTILIZERS,Manufacturers & distributors of apparels/\ngar...
1459,ZUARIIND,ZUARI INDUSTRIES LIMITED,Process Industries,Process Industries,Companies providing dredging and related\nserv...
1460,ZYDUSLIFE,Zydus Lifesciences Limited,Health Technology,Health Technology,"Companies engaged in software\ndevelopment, IT..."
1461,ZYDUSWELL,Zydus Wellness Limited,Packaged Foods,Packaged Foods,Manufacturers of civil and military\naerospace...